/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/manFace/PeterHeadSimpleHairMesh.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HairSimple.geometry}
        material={materials.HairSimpleMat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LashesSimple.geometry}
        material={materials.HairSimpleMat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BrowsSimple.geometry}
        material={materials.HairSimpleMat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MoustacheSimple.geometry}
        material={materials.HairSimpleMat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.White_Scarf.geometry}
        material={materials.ScarfWhite}
        position={[-0.006, 0.13, -0.008]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Red_Collar.geometry}
        material={materials.RedCloth}
        position={[0.008, 0.148, 0.02]}
        rotation={[0, 0.273, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EyeLeft.geometry}
        material={materials.EyeExternal}
        position={[0.026, 0.248, 0.065]}
        rotation={[0.076, -0.275, -0.015]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EyeInternal.geometry}
          material={materials.EyeInternal}
          position={[-0.032, -0.006, -0.129]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EyeRight.geometry}
        material={materials.EyeExternal}
        position={[-0.032, 0.249, 0.058]}
        rotation={[-3.05, 0.376, 0.013]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EyeInternal001.geometry}
          material={materials.EyeInternal}
          position={[0.032, 0.006, 0.129]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PeterHead.geometry}
        material={nodes.PeterHead.material}
        position={[-0.001, 0.211, 0.026]}
        rotation={[1.687, -0.004, 0.118]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Button.geometry}
        material={materials.Buttons}
        position={[0.052, 0.059, 0.041]}
        rotation={[-0.515, 0.807, 0.408]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Green_Jacket.geometry}
        material={materials.GreenCloth}
        position={[0.008, 0.143, 0.02]}
      />
    </group>
  )
}

useGLTF.preload('/PeterHeadSimpleHairMesh.glb')


